#!/usr/bin/env bash
# GENERATED by tmux/generate-theme.sh — DO NOT EDIT.
ram=$(free -m | awk '/^Mem/{print $3"MB"}')
cpu=$("$HOME/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" --interval 2 --averages-count 0 --graph-lines 0 | tr -d '\0' | awk '{print $NF}')
disk=$(df -h / | awk 'NR==2{print $5}')
line=" $ram  $cpu  $disk"
bat=$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -1)
[ -n "$bat" ] && line="$line  $(cat "$bat/capacity" 2>/dev/null)%"
printf '%s' "$line"
