#!/usr/bin/env bash
#
# Install the terminal/UI fonts and point alacritty + KDE at whichever is
# available.
#
#   Preferred : patched MonoLisaCode Nerd Font from private/fonts/patched
#               (MonoLisa + Nerd Font glyphs, supplied out-of-band by
#               scripts/20-private.sh).
#   Fallback  : the bundled 0xProto Nerd Font (fonts/0xProto, OFL, always in the
#               repo) — used when the private assets are skipped/unavailable.
#
# The chosen family is written to ~/.config/alacritty/font.toml (imported by the
# stowed alacritty.toml) and set as the KDE monospace font. The font.toml lives
# in ~/.config rather than the stow package because the choice is per-machine.
# Re-runnable.
#
set -euo pipefail

DOTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DEST="$HOME/.local/share/fonts"
MONO_SRC="$DOTS_DIR/private/fonts/patched"
FALLBACK_SRC="$DOTS_DIR/fonts/0xProto"

MONO_FAMILY="MonoLisaCode Nerd Font"
FALLBACK_FAMILY="0xProto Nerd Font Mono"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }

install_ttfs() { # $1 = source dir, $2 = label
  local src="$1" label="$2" n=0
  [ -d "$src" ] || { log "no $label fonts at $src — skipping"; return 0; }
  while IFS= read -r -d '' f; do
    install -Dm644 "$f" "$DEST/$(basename "$f")"
    n=$((n + 1))
  done < <(find "$src" -type f \( -iname '*.ttf' -o -iname '*.otf' \) -print0)
  log "installed $n $label font file(s)"
}

mkdir -p "$DEST"

# Always install the bundled fallback; add MonoLisa when the private assets are
# present.
install_ttfs "$FALLBACK_SRC" "0xProto (fallback)"
[ -d "$MONO_SRC" ] && install_ttfs "$MONO_SRC" "MonoLisa"

fc-cache -f "$DEST" >/dev/null 2>&1 || true

# --- pick the active family -------------------------------------------------
if fc-list | grep -qi "$MONO_FAMILY"; then
  FAMILY="$MONO_FAMILY"
else
  FAMILY="$FALLBACK_FAMILY"
fi
log "active monospace font: $FAMILY"

# --- alacritty: generated font import ---------------------------------------
ACONF="$HOME/.config/alacritty"
if [ -d "$ACONF" ]; then
  cat > "$ACONF/font.toml" <<EOF
# Generated by scripts/30-fonts.sh — MonoLisa when the private font is present,
# else the bundled 0xProto Nerd Font. Bold/italic derive from this family.
[font.normal]
family = "$FAMILY"
style = "Regular"
EOF
  log "wrote $ACONF/font.toml"
else
  log "$ACONF not present (alacritty package not stowed?) — skipping font.toml"
fi

# --- KDE default monospace font ---------------------------------------------
# Spec captured verbatim from System Settings (Plasma 6 / Qt6 format); only the
# family varies.
if command -v kwriteconfig6 >/dev/null 2>&1; then
  kwriteconfig6 --file kdeglobals --group General --key "fixed" \
    "$FAMILY,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
  log "set KDE monospace font to $FAMILY"
fi
