#!/usr/bin/env bash
#
# Install the fontconfig drop-in that gives confined snaps the same generic font
# families as the KDE host. Installed as a real file (not stowed, not symlinked)
# because conf.d symlinks into /usr/share/fontconfig dangle inside snaps. Needs
# sudo. Re-runnable.
#
set -euo pipefail

DOTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="$DOTS_DIR/system/fontconfig"
DEST="/etc/fonts/conf.d"

log() { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
err() { printf '\033[1;31m!!\033[0m %s\n' "$*" >&2; }

[ -d "$SRC" ] || { log "no system/fontconfig, nothing to do"; exit 0; }

for f in "$SRC"/*.conf; do
  [ -f "$f" ] || continue
  name="$(basename "$f")"
  # A malformed drop-in makes every fontconfig client noisy, so parse it first.
  if command -v xmllint >/dev/null 2>&1 && ! xmllint --noout "$f" 2>/dev/null; then
    err "skip $name (not well-formed XML)"
    continue
  fi
  sudo install -m 0644 -o root -g root "$f" "$DEST/$name"
  log "installed $DEST/$name"
done

# --- make the user's own fonts visible to snaps -----------------------------
# A snap's fonts.conf scans `<dir prefix="xdg">fonts</dir>`, but snap launchers
# repoint XDG_DATA_HOME at $SNAP_USER_DATA, so ~/.local/share/fonts is never
# scanned and MonoLisa goes missing. Declare it by absolute path instead; the
# home interface already lets snaps read it. Generated because the path is
# per-user.
GEN="$(mktemp)"
trap 'rm -f "$GEN"' EXIT
{
  printf '<?xml version="1.0"?>\n'
  printf '<!DOCTYPE fontconfig SYSTEM "urn:fontconfig:fonts.dtd">\n'
  printf '<fontconfig>\n'
  printf '  <description>User font dirs by absolute path, for confined snaps</description>\n'
  printf '  <!-- Generated by scripts/31-snap-fonts.sh. Edit that, not this. -->\n'
  for d in "$HOME/.local/share/fonts" "$HOME/.fonts"; do
    [ -d "$d" ] && printf '  <dir>%s</dir>\n' "$d"
  done
  printf '</fontconfig>\n'
} > "$GEN"

if command -v xmllint >/dev/null 2>&1 && ! xmllint --noout "$GEN" 2>/dev/null; then
  err "generated user-fontdir drop-in is not well-formed — skipping"
else
  sudo install -m 0644 -o root -g root "$GEN" "$DEST/98-snap-user-fontdir.conf"
  log "installed $DEST/98-snap-user-fontdir.conf ($HOME/.local/share/fonts)"
fi

# Rebuild the host cache and confirm fontconfig still parses cleanly.
if ! fc-cache -f >/dev/null 2>&1; then
  err "fc-cache reported an error — check $DEST for a malformed drop-in"
  exit 1
fi
log "host font cache rebuilt"

log "host generics: sans=$(fc-match -f '%{family}' sans-serif), mono=$(fc-match -f '%{family}' monospace)"
