#!/usr/bin/env bash
#
# Generate tmux/.config/tmux/theme.conf from theme/palette.sh — colors, styles,
# and the powerline status bar.
#   left:  session name  (blue)
#   mid:   window list   (current highlighted; hard+soft separators)
#   right: metrics grey (ram/cpu/disk/battery, iconed) | clock green | host blue
# Sourced by tmux.conf. Not stowed (see --ignore in install.sh).
#
set -euo pipefail

PKG_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# shellcheck source=../theme/palette.sh
. "$PKG_DIR/../theme/palette.sh"

out="$PKG_DIR/.config/tmux/theme.conf"
mkdir -p "$(dirname "$out")"

# Powerline separators + right-side icons, by codepoint (\u escapes) so the
# bytes are reliable. Left hard/soft point right (E0B0/E0B1); right point left
# (E0B2/E0B3).
L_HARD=$(printf ''); L_SOFT=$(printf '')
R_HARD=$(printf ''); R_SOFT=$(printf '')
RAM_ICON=$(printf '\uefc5'); CPU_ICON=$(printf '\uf2db'); HDD_ICON=$(printf '\uf1c0')
BAT_ICON=$(printf '\uf240')

# Grey "metrics" panel content comes from a generated helper so tmux never sees
# the awk/pipe/% (avoids #() quoting + strftime mangling). Icons baked in from
# the vars above; battery detected at runtime.
metrics="$PKG_DIR/.config/tmux/metrics.sh"
cat > "$metrics" <<MEOF
#!/usr/bin/env bash
# GENERATED by tmux/generate-theme.sh — DO NOT EDIT.
ram=\$(free -m | awk '/^Mem/{print \$3"MB"}')
cpu=\$("\$HOME/.config/tmux/plugins/tmux-mem-cpu-load/tmux-mem-cpu-load" --interval 2 --averages-count 0 --graph-lines 0 | tr -d '\0' | awk '{print \$NF}')
disk=\$(df -h / | awk 'NR==2{print \$5}')
line="${RAM_ICON} \$ram ${CPU_ICON} \$cpu ${HDD_ICON} \$disk"
bat=\$(ls -d /sys/class/power_supply/BAT* 2>/dev/null | head -1)
[ -n "\$bat" ] && line="\$line ${BAT_ICON} \$(cat "\$bat/capacity" 2>/dev/null)%"
printf '%s' "\$line"
MEOF
chmod +x "$metrics"

# right: metrics (grey) | clock (green) | host (blue), hard separators.
SR="#[fg=$C_GREY,bg=$C_BG]${R_HARD}#[fg=$C_GREEN,bg=$C_GREY] #(\$HOME/.config/tmux/metrics.sh) "
SR+="#[fg=$C_GREEN,bg=$C_GREY]${R_HARD}#[fg=$C_BLACK,bg=$C_GREEN] %H:%M "
SR+="#[fg=$C_BLUE,bg=$C_GREEN]${R_HARD}#[fg=$C_BLACK,bg=$C_BLUE] #h "
SR+="#[default]"

cat > "$out" <<EOF
# GENERATED from theme/palette.sh by tmux/generate-theme.sh — DO NOT EDIT.

# --- base styles ------------------------------------------------------------
set -g mode-style "fg=$C_FG,bg=$C_BG_HIGHLIGHT"
set -g message-style "fg=$C_BG,bg=$C_YELLOW"
set -g message-command-style "fg=$C_BG,bg=$C_YELLOW"
set -g copy-mode-match-style "fg=$C_BG,bg=$C_FG_DIM"
set -g copy-mode-current-match-style "fg=$C_BG,bg=$C_YELLOW"
set -g copy-mode-mark-style "fg=$C_FG,bg=$C_HOTPINK"
set -g pane-border-style "fg=$C_GREY"
set -g pane-active-border-style "fg=$C_GREEN"

# --- status bar -------------------------------------------------------------
set -g status on
set -g status-interval 2
set -g status-justify left
set -g status-style "fg=$C_GREEN,bg=$C_BG"
set -g status-left-length 60
set -g status-right-length 150

# left: session (blue) tapering via a blue arrow onto the black window area
set -g status-left "#[fg=$C_BLACK,bg=$C_BLUE] #S #[fg=$C_BLUE,bg=$C_BG]${L_HARD}#[fg=$C_GREEN,bg=$C_BG]"

# windows: current = green pill with black-on-green caps; inactive = green text
# on black with a soft index|name divider.
set -g window-status-separator ""
set -g window-status-format "#[fg=$C_GREEN,bg=$C_BG] #I#{?window_flags,#F, }#[fg=$C_GREY]${L_SOFT}#[fg=$C_GREEN] #W "
set -g window-status-current-format "#[fg=$C_BG,bg=$C_GREEN]${L_HARD}#[fg=$C_BLACK,bg=$C_GREEN] #I#F #[fg=$C_BLACK]${L_SOFT}#[fg=$C_BLACK] #W #[fg=$C_GREEN,bg=$C_BG]${L_HARD}#[fg=$C_GREEN,bg=$C_BG]"

# right: metrics | host | clock (built as \$SR above)
set -g status-right "$SR"
EOF

echo "wrote $out"
