-- Plugin modules. Each require()d module installs its plugin(s) via vim.pack
-- and configures them. Keymaps live centrally in config/keymaps.lua.
require("plugins.tokyonight")
require("plugins.lualine")
require("plugins.neo-tree")
require("plugins.tmux-navigator")
require("plugins.conform")
require("plugins.lsp")
require("plugins.which-key")
require("plugins.telescope")
require("plugins.mini")
require("plugins.todo-comments")
require("plugins.trouble")
require("plugins.colorizer")
require("plugins.treesitter")
require("plugins.treesitter-textobjects")
require("plugins.git")
require("plugins.guess-indent")
require("plugins.flash")
require("plugins.indent-blankline")
require("plugins.markdown-preview")
require("plugins.multicursor")
require("plugins.nvim-surround")
